### ISSUE TITLE
Create servlet to check which scene is currently active

### ISSUE THREAD

**Issue by champgm** [champgm/hue-stuff#41]
There's no API to tell which scene is currently active, but that would be really nice for the front-end to be able to tell you which scene is currently active. Granted, this will be a little weird as, if you mess with a single light, the light states may not match any given scene, but it would be nice to have some kind of feedback.

This will only work with V2 scenes which store their expected light states. The servlet will need to retrieve all scenes and lightstates and then compare the current light states to the ones in each scene to see if there is a match. 

AC: 
Servlet which will get the currently active scene
Command which will do the same
Unit test in HueBridgeGetterTest to test this functionality

**Comment by zhna123** [comment]
Does activate one scene deactivate the other scene that is currently on?

**Comment by champgm** [comment]
Offline discussion, but no, scenes are messy and complicated and just overwrite on top of each other when activated.

**Comment by champgm** [comment]
#47
